export const demoMembershipDoctors: any[] = [
  {
    id: "m1",
    clinicId: "c1",
    doctorId: "d1",
    fee: 500,
    maxAppointments: 10,
    discount: 50,
    isActive: true,
    joinedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    doctor: {
      id: "d1",
      userId: "u1",
      hospital: "City Clinic",
      user: {
        name: "John Doe",
        email: "john.doe@example.com",
        image: null,
      },
      specializations: [
        { id: "s1", name: "Cardiology" },
        { id: "s2", name: "Internal Medicine" },
      ],
    },
    clinic: {
      id: "c1",
      name: "City Clinic",
      email: "admin@cityclinic.com",
      image: null,
      user: {
        name: "Clinic Admin",
        email: "admin@cityclinic.com",
        image: null,
      },
    },
    schedules: [
      {
        id: "sch1",
        membershipId: "m1",
        opening: "09:00 AM",
        close: "12:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "sch2",
        membershipId: "m1",
        opening: "02:00 PM",
        close: "06:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "m2",
    clinicId: "c2",
    doctorId: "d2",
    fee: 700,
    maxAppointments: 8,
    discount: 0,
    isActive: true,
    joinedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    doctor: {
      id: "d2",
      userId: "u2",
      hospital: "Green Valley Hospital",
      user: {
        name: "Jane Smith",
        email: "jane.smith@example.com",
        image: null,
      },
      specializations: [{ id: "s3", name: "Pediatrics" }],
    },
    clinic: {
      id: "c2",
      name: "Green Valley Hospital",
      email: "info@greenvalley.com",
      image: null,
      user: {
        name: "Hospital Admin",
        email: "admin@greenvalley.com",
        image: null,
      },
    },
    schedules: [
      {
        id: "sch3",
        membershipId: "m2",
        opening: "08:00 AM",
        close: "01:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "sch4",
        membershipId: "m2",
        opening: "03:00 PM",
        close: "07:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "m3",
    clinicId: "c3",
    doctorId: "d3",
    fee: 600,
    maxAppointments: 12,
    discount: 20,
    isActive: true,
    joinedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    doctor: {
      id: "d3",
      userId: "u3",
      hospital: "Sunrise Medical Center",
      user: {
        name: "Michael Lee",
        email: "michael.lee@example.com",
        image: null,
      },
      specializations: [
        { id: "s4", name: "Dermatology" },
        { id: "s5", name: "Cosmetic Surgery" },
      ],
    },
    clinic: {
      id: "c3",
      name: "Sunrise Medical Center",
      email: "info@sunrise.com",
      image: null,
      user: {
        name: "Sunrise Admin",
        email: "admin@sunrise.com",
        image: null,
      },
    },
    schedules: [
      {
        id: "sch5",
        membershipId: "m3",
        opening: "10:00 AM",
        close: "01:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "sch6",
        membershipId: "m3",
        opening: "04:00 PM",
        close: "08:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];
