export const bloodGroup = [
  { value: "A+", label: "A Positive (A+)" },
  { value: "A-", label: "A Negative (A-)" },
  { value: "B+", label: "B Positive (B+)" },
  { value: "B-", label: "B Negative (B-)" },
  { value: "AB+", label: "AB Positive (AB+)" },
  { value: "AB-", label: "AB Negative (AB-)" },
  { value: "O+", label: "O Positive (O+)" },
  { value: "O-", label: "O Negative (O-)" },
];
// বাংলা ডাটা অবজেক্ট
export const doctorDepartments = [
  {
    id: "med-01",
    label: "মেডিসিন বিশেষজ্ঞ",
    value: "medicine",
    icon: "💊",
    count: 0,
  },
  {
    id: "card-01",
    label: "হৃদরোগ (হার্ট) বিশেষজ্ঞ",
    value: "cardiology",
    icon: "💓",
    count: 0,
  },
  {
    id: "neuro-01",
    label: "মস্তিষ্ক ও স্নায়ু বিশেষজ্ঞ",
    value: "neurology",
    icon: "🧠",
    count: 0,
  },
  {
    id: "ortho-01",
    label: "হাড় ও জোড়া বিশেষজ্ঞ",
    value: "orthopedics",
    icon: "🦴",
    count: 0,
  },
  {
    id: "surg-01",
    label: "জেনারেল সার্জারি",
    value: "general-surgery",
    icon: "🔪",
    count: 0,
  },
  {
    id: "neph-01",
    label: "কিডনি বিশেষজ্ঞ",
    value: "nephrology",
    icon: "💧",
    count: 0,
  },
  {
    id: "gastro-01",
    label: "লিভার ও পাকস্থলী",
    value: "gastroenterology",
    icon: "🧪",
    count: 0,
  },
  {
    id: "pulmo-01",
    label: "বক্ষব্যাধি ও শ্বাসকষ্ট",
    value: "pulmonology",
    icon: "💓",
    count: 0,
  },
  {
    id: "endo-01",
    label: "হরমোন ও ডায়াবেটিস",
    value: "endocrinology",
    icon: "🩸",
    count: 0,
  },
  {
    id: "derma-01",
    label: "চর্ম ও যৌন রোগ বিশেষজ্ঞ",
    value: "dermatology",
    icon: "✨",
    count: 0,
  },
  {
    id: "psy-01",
    label: "মানসিক রোগ",
    value: "psychiatry",
    icon: "🧘",
    count: 0,
  },
  {
    id: "pedia-01",
    label: "শিশু বিশেষজ্ঞ",
    value: "pediatrics",
    icon: "👶",
    count: 0,
  },
  {
    id: "gyn-01",
    label: "গাইনী এন্ড অবস বিশেষজ্ঞ",
    value: "gynecology",
    icon: "👩‍⚕️",
    count: 0,
  },
  {
    id: "uro-01",
    label: "ইউরোলজি বিশেষজ্ঞ",
    value: "urology",
    icon: "🚽",
    count: 0,
  },
  {
    id: "ent-01",
    label: "নাক, কান ও গলা",
    value: "ent",
    icon: "👂",
    count: 0,
  },
  {
    id: "eye-01",
    label: "চক্ষু বিশেষজ্ঞ",
    value: "ophthalmology",
    icon: "👁️",
    count: 0,
  },
  {
    id: "onco-01",
    label: "ক্যান্সার বিশেষজ্ঞ",
    value: "oncology",
    icon: "🎗️",
    count: 0,
  },
  {
    id: "dental-01",
    label: "দন্ত চিকিৎসা",
    value: "dentistry",
    icon: "🦷",
    count: 0,
  },
  {
    id: "rheum-01",
    label: "বাত-ব্যথা ও রিউমাটোলজি",
    value: "rheumatology",
    icon: "🏃",
    count: 0,
  },
  {
    id: "hema-01",
    label: "রক্তরোগ বিশেষজ্ঞ",
    value: "hematology",
    icon: "💉",
    count: 0,
  },
  {
    id: "pmr-01",
    label: "ফিজিক্যাল মেডিসিন",
    value: "physical-medicine",
    icon: "♿",
    count: 0,
  },
  {
    id: "nutri-01",
    label: "পুষ্টি ও ডায়েট",
    value: "nutrition",
    icon: "🍎",
    count: 0,
  },
  {
    id: "neo-01",
    label: "নবজাতক বিশেষজ্ঞ",
    value: "neonatology",
    icon: "🍼",
    count: 0,
  },
  {
    id: "radio-01",
    label: "রেডিওলজি ও ইমেজিং",
    value: "radiology",
    icon: "🩻",
    count: 0,
  },
  {
    id: "anes-01",
    label: "অ্যানেস্থেসিওলজি",
    value: "anesthesiology",
    icon: "😴",
    count: 0,
  },
  {
    id: "path-01",
    label: "প্যাথলজি",
    value: "pathology",
    icon: "🔬",
    count: 0,
  },
  {
    id: "emg-01",
    label: "জরুরি চিকিৎসা",
    value: "emergency-medicine",
    icon: "🚑",
    count: 0,
  },
  {
    id: "inf-01",
    label: "ইনফেকশাস ডিজিজ",
    value: "infectious-disease",
    icon: "🦠",
    count: 0,
  },
];
export const genderOptions = [
  { value: "MALE", label: "MALE" },
  { value: "FEMALE", label: "FEMALE" },
];
export const Gender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
};
export const BASE_URL =
  process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000/api/v1";
export const UserRole = {
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
  ADMIN: "ADMIN",
  CLINIC: "CLINIC",
};
export const nameRegex = /^[A-Za-z\u0980-\u09FF\s.]+$/;
// ফোন নম্বর: ইংরেজি (017...) এবং বাংলা (০১৭১...) উভয় সংখ্যা সাপোর্ট করবে
export const phoneRegex = /^(?:\+88|88)?(?:01[3-9]\d{8}|[০-৯]{11})$/;
